# Generated by Django 6.0.5 on 2026-06-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studymain', '0002_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
