# Generated by Django 6.0.5 on 2026-06-17 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studymain', '0003_notes_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studymain.folder'),
        ),
    ]
