# Generated by Django 6.0.5 on 2026-07-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studymain', '0005_alter_folder_name_alter_notes_name_flashcards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcards',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='flashcards',
            name='notes',
        ),
        migrations.AddField(
            model_name='flashcards',
            name='flashcard_a',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcards',
            name='flashcard_q',
            field=models.TextField(blank=True, null=True),
        ),
    ]
