# Generated by Django 6.0.5 on 2026-07-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studymain', '0006_remove_flashcards_folder_remove_flashcards_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcards',
            name='flashcard_q',
            field=models.CharField(blank=True, null=True),
        ),
    ]
