# Generated by Django 6.0.5 on 2026-07-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studymain', '0007_alter_flashcards_flashcard_q'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcards',
            name='flashcard_q',
            field=models.TextField(blank=True, null=True),
        ),
    ]
