# Generated by Django 6.0.5 on 2026-07-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studymain', '0009_studyset_flashcard_delete_flashcards'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizDistractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
