# Generated by Django 6.0.5 on 2026-07-07 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studymain', '0010_quizdistractors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizDistractors',
        ),
    ]
