# Generated by Django 6.0.7 on 2026-07-22 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studymain', '0012_flashcard_user_studyset_user_alter_folder_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='notes',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='studymain.folder'),
        ),
    ]
