# Generated by Django 6.0.7 on 2026-07-22 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studymain', '0013_alter_folder_options_alter_notes_folder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={},
        ),
    ]
